version: '3.1'
services:
  postgres:
    image: 'postgres:15.2-alpine'
    ports:
      - 6543:5432
    command: postgres -c log_statement=all
    environment:
      POSTGRES_USER: daiichi_user
      POSTGRES_DB: daiichi_db
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-secret}"
